"""Inital schema

Revision ID: 6cdbe82052f5
Revises: 
Create Date: 2026-03-16 21:45:05.961984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdbe82052f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Branch',
    sa.Column('BranchID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.String(length=100), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('BranchID')
    )
    op.create_table('DeliveryPerson',
    sa.Column('DeliveryPersonID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('DeliveryPersonID')
    )
    op.create_table('Ingredient',
    sa.Column('IngredientID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('IngredientID')
    )
    op.create_table('Item',
    sa.Column('ItemID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ItemID')
    )
    op.create_table('Status',
    sa.Column('StatusID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('StatusID')
    )
    op.create_table('User',
    sa.Column('UserID', sa.UUID(), nullable=False),
    sa.Column('AppID', sa.String(length=100), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=30), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('AppID')
    )
    op.create_table('BranchItem',
    sa.Column('BranchID', sa.UUID(), nullable=False),
    sa.Column('ItemID', sa.UUID(), nullable=False),
    sa.Column('IsAvalible', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branch.BranchID'], ),
    sa.ForeignKeyConstraint(['ItemID'], ['Item.ItemID'], ),
    sa.PrimaryKeyConstraint('BranchID', 'ItemID')
    )
    op.create_table('IngredientBranch',
    sa.Column('BranchID', sa.UUID(), nullable=False),
    sa.Column('IngredientID', sa.UUID(), nullable=False),
    sa.Column('IsAvalible', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branch.BranchID'], ),
    sa.ForeignKeyConstraint(['IngredientID'], ['Ingredient.IngredientID'], ),
    sa.PrimaryKeyConstraint('BranchID', 'IngredientID')
    )
    op.create_table('IngredientItem',
    sa.Column('IngredientID', sa.UUID(), nullable=False),
    sa.Column('ItemID', sa.UUID(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IngredientID'], ['Ingredient.IngredientID'], ),
    sa.ForeignKeyConstraint(['ItemID'], ['Item.ItemID'], ),
    sa.PrimaryKeyConstraint('IngredientID', 'ItemID')
    )
    op.create_table('Order',
    sa.Column('OrderID', sa.UUID(), nullable=False),
    sa.Column('UserID', sa.UUID(), nullable=False),
    sa.Column('StatusID', sa.Integer(), nullable=False),
    sa.Column('BranchID', sa.UUID(), nullable=False),
    sa.Column('TotalAmount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('CreateAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BranchID'], ['Branch.BranchID'], ),
    sa.ForeignKeyConstraint(['StatusID'], ['Status.StatusID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('UserAddress',
    sa.Column('UserAddressID', sa.UUID(), nullable=False),
    sa.Column('UserID', sa.UUID(), nullable=False),
    sa.Column('Country', sa.String(length=100), nullable=False),
    sa.Column('State', sa.String(length=100), nullable=False),
    sa.Column('City', sa.String(length=100), nullable=False),
    sa.Column('Neighborhood', sa.String(length=100), nullable=False),
    sa.Column('ZipCode', sa.String(length=30), nullable=False),
    sa.Column('ExtNum', sa.String(length=100), nullable=False),
    sa.Column('IntNum', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], ),
    sa.PrimaryKeyConstraint('UserAddressID')
    )
    op.create_table('Delivery',
    sa.Column('DeliveryID', sa.UUID(), nullable=False),
    sa.Column('OrderID', sa.UUID(), nullable=False),
    sa.Column('DeliveryPersonID', sa.UUID(), nullable=False),
    sa.Column('StatusID', sa.Integer(), nullable=False),
    sa.Column('EstimatedDeliveryTime', sa.DateTime(), nullable=True),
    sa.Column('ActualDeliveryTime', sa.DateTime(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['DeliveryPersonID'], ['DeliveryPerson.DeliveryPersonID'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['Order.OrderID'], ),
    sa.ForeignKeyConstraint(['StatusID'], ['Status.StatusID'], ),
    sa.PrimaryKeyConstraint('DeliveryID')
    )
    op.create_table('OrderItem',
    sa.Column('OrderID', sa.UUID(), nullable=False),
    sa.Column('ItemID', sa.UUID(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ItemID'], ['Item.ItemID'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['Order.OrderID'], ),
    sa.PrimaryKeyConstraint('OrderID', 'ItemID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderItem')
    op.drop_table('Delivery')
    op.drop_table('UserAddress')
    op.drop_table('Order')
    op.drop_table('IngredientItem')
    op.drop_table('IngredientBranch')
    op.drop_table('BranchItem')
    op.drop_table('User')
    op.drop_table('Status')
    op.drop_table('Item')
    op.drop_table('Ingredient')
    op.drop_table('DeliveryPerson')
    op.drop_table('Branch')
    # ### end Alembic commands ###